
spring:
  application:
    name: story
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.100.160:3306/love_story?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: RvcDDt&Qsfk8BEiDoi#g

server:
  port: 9001



wx:
  appid: wx2b726168cd838629
  secret: f6d250483427fe6d3cfc4a196f3a1f5f
  grant_type: authorization_code