spring:
  application:
    name: story
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.100.160:3306/love_story?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: RvcDDt&Qsfk8BEiDoi#g
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB

server:
  port: 9001
  tomcat:
    basedir: ./temp
    max-connections: 1000
    accept-count: 1000

mybatis-plus:
  configuration:  #sql日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      update-strategy: ignored
      logic-delete-value: 1  # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0  # 逻辑未删除值(默认为 0)
mybatis:
  configuration:
    map-underscore-to-camel-case: true

go-fastdfs:
  uploadUrl: http://47.102.100.160:8080/group1/upload
  deleteUrl: http://47.102.100.160:8080/group1/delete

wx:
  appid: wx2b726168cd838629
  secret: f6d250483427fe6d3cfc4a196f3a1f5f
  grant_type: authorization_code